#!/usr/bin/env sh
# postprovision-write-tests-env.sh
# ---------------------------------------------------------------------------
# Exports azd env → options-infra/ai-gateway-basic-rbac/tests/.env so pytest
# can authenticate as each persona SP and know the deployed Foundry/APIM
# endpoints.
#
# The .env is gitignored (see .gitignore at repo root — matches *.env pattern).
# ---------------------------------------------------------------------------
set -eu

script_dir=$(cd "$(dirname "$0")" && pwd)
env_file="${script_dir}/../ai-gateway-basic-rbac/tests/.env"
mkdir -p "$(dirname "$env_file")"

# Helper: azd env get-value writes "key not found" to stdout on miss, exits 1.
get_val() {
  val=$(azd env get-value "$1" 2>/dev/null) || val=""
  echo "$val"
}

tenant_id=$(get_val RBAC_TENANT_ID)
subscription_id=$(az account show --query id -o tsv)
resource_group=$(get_val AZURE_RESOURCE_GROUP)
if [ -z "$resource_group" ]; then
  resource_group=$(get_val RG)
fi
location=$(get_val AZURE_LOCATION)
foundry_name=$(get_val FOUNDRY_NAME)
project_names=$(get_val FOUNDRY_PROJECT_NAMES)
# FOUNDRY_PROJECT_NAMES is a bicep string[] outputted as JSON — take the first entry.
project_name=$(echo "$project_names" | python3 -c "import json,sys;print(json.loads(sys.stdin.read() or '[]')[0])" 2>/dev/null || echo "")
apim_gateway_url=$(get_val APIM_GATEWAY_URL)
ai_search_name=$(get_val AI_SEARCH_NAME)
ai_search_endpoint=$(get_val AI_SEARCH_ENDPOINT)
rbac_sp_json=$(get_val RBAC_SP_JSON)
rbac_sp_secrets_json=$(get_val RBAC_SP_SECRETS_JSON)

foundry_endpoint="https://${foundry_name}.services.ai.azure.com"

cat > "$env_file" <<EOF
# Auto-generated by postprovision-write-tests-env.sh — do not edit by hand.
AZURE_TENANT_ID=${tenant_id}
AZURE_SUBSCRIPTION_ID=${subscription_id}
AZURE_RESOURCE_GROUP=${resource_group}
AZURE_LOCATION=${location}
FOUNDRY_NAME=${foundry_name}
FOUNDRY_PROJECT_NAME=${project_name}
FOUNDRY_ENDPOINT=${foundry_endpoint}
FOUNDRY_PROJECT_ENDPOINT=${foundry_endpoint}/api/projects/${project_name}
APIM_GATEWAY_URL=${apim_gateway_url}
AI_SEARCH_NAME=${ai_search_name}
AI_SEARCH_ENDPOINT=${ai_search_endpoint}
RBAC_SP_JSON=${rbac_sp_json}
RBAC_SP_SECRETS_JSON=${rbac_sp_secrets_json}
EOF

echo "→ Wrote ${env_file}"
