# postprovision-write-tests-env.ps1 — see postprovision-write-tests-env.sh for contract.
$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $PSCommandPath
$envFile = Join-Path $scriptDir '..\ai-gateway-basic-rbac\tests\.env'
$envDir = Split-Path -Parent $envFile
if (-not (Test-Path $envDir)) { New-Item -ItemType Directory -Path $envDir | Out-Null }

function Get-Val($name) {
  try { azd env get-value $name 2>$null } catch { '' }
}

$tenantId = Get-Val RBAC_TENANT_ID
$subscriptionId = az account show --query id -o tsv
$resourceGroup = Get-Val AZURE_RESOURCE_GROUP
if (-not $resourceGroup) { $resourceGroup = Get-Val RG }
$location = Get-Val AZURE_LOCATION
$foundryName = Get-Val FOUNDRY_NAME
$projectNamesJson = Get-Val FOUNDRY_PROJECT_NAMES
$projectName = ''
try { $projectName = ($projectNamesJson | ConvertFrom-Json)[0] } catch { }
$apimGatewayUrl = Get-Val APIM_GATEWAY_URL
$rbacSpJson = Get-Val RBAC_SP_JSON
$rbacSpSecretsJson = Get-Val RBAC_SP_SECRETS_JSON

$foundryEndpoint = "https://$foundryName.services.ai.azure.com"

@"
# Auto-generated by postprovision-write-tests-env.ps1 — do not edit by hand.
AZURE_TENANT_ID=$tenantId
AZURE_SUBSCRIPTION_ID=$subscriptionId
AZURE_RESOURCE_GROUP=$resourceGroup
AZURE_LOCATION=$location
FOUNDRY_NAME=$foundryName
FOUNDRY_PROJECT_NAME=$projectName
FOUNDRY_ENDPOINT=$foundryEndpoint
FOUNDRY_PROJECT_ENDPOINT=$foundryEndpoint/api/projects/$projectName
APIM_GATEWAY_URL=$apimGatewayUrl
RBAC_SP_JSON=$rbacSpJson
RBAC_SP_SECRETS_JSON=$rbacSpSecretsJson
"@ | Set-Content -Path $envFile -Encoding utf8

Write-Host "→ Wrote $envFile"
