// This bicep files deploys one resource group with the following resources:
// 1. The AI Foundry dependencies, such as VNet and
//    private endpoints for AI Search, Azure Storage and Cosmos DB
// 2. The AI Foundry itself
// 3. Two AI Projects with the capability hosts - in Foundry Standard mode
// 4. LiteLLM container app fronted by a self-signed cert on `liteLlmDomain`
// 5. The self-signed root CA stored in Key Vault and registered in Foundry's
//    trustedCertificates configuration so Foundry can call LiteLLM directly.
targetScope = 'resourceGroup'

@allowed([
  'canadacentral'
])
param location string = 'canadacentral'
param openAiApiBase string
param openAiResourceId string

@description('FQDN covered by the self-signed leaf cert presented by LiteLLM (e.g. litellm.contoso.internal). Generated by scripts/preprovision-litellm-cert.sh.')
param liteLlmDomain string

@secure()
@description('Base64-encoded PFX (leaf cert + key + CA chain) for the LiteLLM custom domain. Bound to the ACA managed environment so ACA terminates TLS for <liteLlmDomain> with this self-signed cert.')
param liteLlmCertPfxBase64 string

@secure()
@description('Password protecting the PFX in liteLlmCertPfxBase64.')
param liteLlmCertPfxPassword string

@secure()
@description('Base64-encoded root CA certificate in PEM format. Stored as a Key Vault secret and registered in Foundry trustedCertificates.')
param liteLlmRootCaPemBase64 string

param projectsCount int = 1

var tags = {
  'created-by': 'option-ai-gateway-LiteLLM-cert'
  'hidden-title': 'Foundry - LiteLLM with private CA trust'
  // SecurityControl: 'Ignore'
}

var valid_config = empty(openAiApiBase) || empty(openAiResourceId)
  ? fail('Both OPENAI_API_BASE and OPENAI_RESOURCE_ID environment variables must be set.')
  : true

// When liteLlmDomain is empty, this is the phase-1 "deploy without custom
// domain" run — the cert vars are allowed to be empty (see README §2). When
// liteLlmDomain is set, all three cert vars must be present.
var valid_cert_config = !empty(liteLlmDomain) && (empty(liteLlmCertPfxBase64) || empty(liteLlmCertPfxPassword) || empty(liteLlmRootCaPemBase64))
  ? fail('LITELLM_DOMAIN is set but cert material is missing. Run the preprovision hook (scripts/preprovision-litellm-cert.sh) to generate it, or clear LITELLM_DOMAIN to deploy without the custom-domain binding.')
  : true

var resourceToken = toLower(uniqueString(resourceGroup().id, location))
var phase2 = !empty(liteLlmDomain)
var trustedCaSecretName = 'litellm-root-ca-pem'
// Same formula as modules/litellm/lite-llm.bicep when no override is passed —
// computing here lets us share the key with the direct Foundry
// connections without taking it through a non-secure module output.
var liteLlmMasterKey = take(uniqueString(resourceToken, 'litellm'), 6)

var openAiParts = split(openAiResourceId, '/')
var openAiName = last(openAiParts)
var openAiSubscriptionId = openAiParts[2]
var openAiResourceGroupName = openAiParts[4]

module identity '../modules/iam/identity.bicep' = {
  name: 'project-identity'
  params: {
    tags: tags
    location: location
    identityName: 'app-${resourceToken}-project-identity'
  }
}

module foundry_identity '../modules/iam/identity.bicep' = if (phase2) {
  name: 'foundry-identity-deployment'
  params: {
    tags: tags
    location: location
    identityName: 'foundry-${resourceToken}-identity'
  }
}

// vnet doesn't have to be in the same RG as the AI Services
// each foundry needs it's own delegated subnet, projects inside of one Foundry share the subnet for the Agents Service
module vnet '../modules/networking/vnet.bicep' = {
  name: 'vnet'
  params: {
    tags: tags
    location: location
    vnetName: 'project-vnet-${resourceToken}'
    extraAgentSubnets: 1
  }
}

module ai_dependencies '../modules/ai/ai-dependencies-with-dns.bicep' = {
  name: 'ai-dependencies-with-dns'
  params: {
    tags: tags
    location: location
    peSubnetName: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.peSubnet.name
    vnetResourceId: vnet.outputs.VIRTUAL_NETWORK_RESOURCE_ID
    resourceToken: resourceToken
    cosmosDBLocation: 'eastus2'
    aiServicesName: '' // create AI services PE later
    aiAccountNameResourceGroupName: ''
  }
}

// Private endpoint for external OpenAI
module openai_private_endpoint '../modules/networking/ai-pe-dns.bicep' = {
  name: 'openai-private-endpoint-and-dns-deployment'
  params: {
    tags: tags
    location: location
    aiAccountName: openAiName
    aiAccountNameResourceGroup: openAiResourceGroupName
    aiAccountSubscriptionId: openAiSubscriptionId
    peSubnetId: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.peSubnet.resourceId
    resourceToken: resourceToken
    existingDnsZones: ai_dependencies.outputs.DNS_ZONES
  }
}

module liteLlmOpenAiRoleAssignment '../modules/iam/role-assignment-cognitiveServices.bicep' = {
  name: 'litellm-openai-user-${resourceToken}'
  scope: resourceGroup(openAiSubscriptionId, openAiResourceGroupName)
  params: {
    accountName: openAiName
    principalId: identity.outputs.MANAGED_IDENTITY_PRINCIPAL_ID
    roleName: 'Cognitive Services OpenAI User'
  }
}

// --------------------------------------------------------------------------------------------------------------
// -- Log Analytics Workspace and App Insights ------------------------------------------------------------------
// --------------------------------------------------------------------------------------------------------------
module logAnalytics '../modules/monitor/loganalytics.bicep' = {
  name: 'log-analytics'
  params: {
    tags: tags
    location: location
    newLogAnalyticsName: 'log-analytics'
    newApplicationInsightsName: 'app-insights'
  }
}

module keyVault '../modules/kv/key-vault.bicep' = {
  name: 'key-vault-deployment-for-foundry'
  params: {
    tags: tags
    location: location
    name: take('kv-foundry-${resourceToken}', 24)
    logAnalyticsWorkspaceId: logAnalytics.outputs.LOG_ANALYTICS_WORKSPACE_RESOURCE_ID
    doRoleAssignments: true
    secrets: phase2
      ? [
          {
            name: trustedCaSecretName
            value: base64ToString(liteLlmRootCaPemBase64)
            contentType: 'application/x-pem-file'
          }
        ]
      : []
    publicAccessEnabled: false
    privateEndpointSubnetId: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.peSubnet.resourceId
    privateEndpointName: 'pe-kv-foundry-${resourceToken}'
    privateDnsZoneResourceId: ai_dependencies.outputs.DNS_ZONES['privatelink.vaultcore.azure.net']!.resourceId
  }
}

module foundry '../modules/ai/ai-foundry.bicep' = if (phase2) {
  name: 'foundry-deployment-${resourceToken}'
  params: {
    tags: tags
    location: location
    managedIdentityResourceId: foundry_identity!.outputs.MANAGED_IDENTITY_RESOURCE_ID
    name: 'ai-foundry-${resourceToken}'
    publicNetworkAccess: 'Enabled'
    agentSubnetResourceId: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.agentSubnet.resourceId // Use the first agent subnet
    deployments: [] // no models
    keyVaultResourceId: keyVault.outputs.KEY_VAULT_RESOURCE_ID
    trustedCertificates: [
      {
        keyVaultId: keyVault.outputs.KEY_VAULT_RESOURCE_ID
        certificates: [
          {
            name: trustedCaSecretName
            version: last(split(keyVault.outputs.KEY_VAULT_SECRETS_URIS_WITH_VERSION[0], '/'))
          }
        ]
      }
    ]
  }
}

module foundryKeyVaultSecretsUser '../modules/iam/role-assignment-keyVaultSecretsUser.bicep' = if (phase2) {
  name: 'foundry-key-vault-secrets-user-${resourceToken}'
  params: {
    keyVaultName: keyVault.outputs.KEY_VAULT_NAME
    principalId: foundry_identity!.outputs.MANAGED_IDENTITY_PRINCIPAL_ID
  }
}

module identities '../modules/iam/identity.bicep' = [
  for i in range(1, 3): if (phase2) {
    name: 'ai-project-${i}-identity-${resourceToken}'
    params: {
      tags: tags
      location: location
      identityName: 'ai-project-${i}-identity-${resourceToken}'
    }
  }
]

@batchSize(1)
module projects '../modules/ai/ai-project-with-caphost.bicep' = [
  for i in range(1, projectsCount): if (phase2) {
    name: 'ai-project-${i}-with-caphost-${resourceToken}'
    params: {
      tags: tags
      location: location
      foundryName: foundry!.outputs.FOUNDRY_NAME
      project_description: 'AI Project ${i} ${resourceToken}'
      display_name: 'AI Project ${i} ${resourceToken}'
      projectId: i
      aiDependencies: ai_dependencies.outputs.AI_DEPENDECIES
      existingAiResourceId: null
      managedIdentityResourceId: identities[i - 1].outputs.MANAGED_IDENTITY_RESOURCE_ID
      appInsightsResourceId: logAnalytics.outputs.APPLICATION_INSIGHTS_RESOURCE_ID
    }
    dependsOn: [
      foundryKeyVaultSecretsUser
    ]
  }
]

module dnsAca 'br/public:avm/res/network/private-dns-zone:0.8.0' = {
  name: 'dns-aca'
  params: {
    tags: tags
    location: 'global'
    name: 'privatelink.${location}.azurecontainerapps.io'
    virtualNetworkLinks: [
      {
        virtualNetworkResourceId: vnet.outputs.VIRTUAL_NETWORK_RESOURCE_ID
      }
    ]
  }
}

module dnsPostgress 'br/public:avm/res/network/private-dns-zone:0.8.0' = {
  name: 'dns-postgress'
  params: {
    tags: tags
    location: 'global'
    name: 'privatelink.postgres.database.azure.com'
    virtualNetworkLinks: [
      {
        virtualNetworkResourceId: vnet.outputs.VIRTUAL_NETWORK_RESOURCE_ID
      }
    ]
  }
}

var litellmStaticModels = [
  {
    name: 'gpt-4.1-mini'
    properties: {
      model: {
        name: 'gpt-4.1-mini'
        version: '2025-01-01-preview'
        format: 'OpenAI'
      }
    }
  }
  {
    name: 'gpt-4o'
    properties: {
      model: {
        name: 'gpt-4o'
        version: '2025-01-01-preview'
        format: 'OpenAI'
      }
    }
  }
  {
    name: 'gpt-5-mini'
    properties: {
      model: {
        name: 'gpt-5-mini'
        version: '2025-04-01-preview'
        format: 'OpenAI'
      }
    }
  }
  {
    name: 'o3-mini'
    properties: {
      model: {
        name: 'o3-mini'
        version: '2025-01-01-preview'
        format: 'OpenAI'
      }
    }
  }
]

module liteLlm '../modules/litellm/lite-llm.bicep' = {
  name: 'lite-llm-deployment-${resourceToken}'
  params: {
    tags: tags
    location: location
    resourceToken: resourceToken
    identityResourceId: identity.outputs.MANAGED_IDENTITY_RESOURCE_ID
    logAnalyticsWorkspaceResourceId: logAnalytics.outputs.LOG_ANALYTICS_WORKSPACE_RESOURCE_ID
    appInsightsConnectionString: logAnalytics.outputs.APPLICATION_INSIGHTS_CONNECTION_STRING
    virtualNetworkResourceId: vnet.outputs.VIRTUAL_NETWORK_RESOURCE_ID
    privateEndpointSubnetId: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.peSubnet.resourceId
    acaSubnetResourceId: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.extraAgentSubnets[0].resourceId
    keyVaultDnsZoneResourceId: ai_dependencies.outputs.DNS_ZONES['privatelink.vaultcore.azure.net']!.resourceId
    postgressDnsZoneResourceId: dnsPostgress.outputs.resourceId
    openAiApiBase: openAiApiBase
    useAzureManagedIdentity: true
    aiFoundryName: 'ai-foundry-${resourceToken}'
    litlLlmPublicFqdn: 'http://${publicIpAddress.outputs.ipAddress}'
    // Self-signed cert + custom domain wiring (this is the "cert" variant).
    // The PFX is bound to the ACA managed environment; ACA terminates TLS at
    // its ingress with this cert for the customDomain hostname. The LiteLLM
    // container itself does NOT serve TLS — ACA HTTP ingress would conflict
    // with end-to-end TLS.
    customDomain: liteLlmDomain
    certPfxBase64: liteLlmCertPfxBase64
    certPfxPassword: liteLlmCertPfxPassword
    // Connections are created below after Foundry has registered the root CA.
    createFoundryConnections: false
    // Share the master key with the direct connections without
    // routing it through a (non-secure) module output.
    liteLlmMasterKeyOverride: liteLlmMasterKey
    liteLlmConfigYaml: '''
model_list:
  - model_name: gpt-4.1-mini
    litellm_params:
      model: azure/gpt-4.1-mini
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_version: "2025-01-01-preview"
  - model_name: gpt-4o
    litellm_params:
      model: azure/gpt-4o
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_version: "2025-01-01-preview"      
  - model_name: gpt-5-mini
    litellm_params:
      model: azure/gpt-5-mini
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_version: "2025-04-01-preview"
  - model_name: o3-mini
    litellm_params:
      model: azure/o3-mini
      api_base: os.environ/AZURE_API_BASE # runs os.getenv("AZURE_API_BASE")
      api_version: "2025-01-01-preview"

general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  drop_params: true
  enable_azure_ad_token_refresh: true
  callbacks: ["otel"]  # list of callbacks - runs on success and failure    

callback_settings:
  otel:
    message_logging: True
    '''
    staticModels: litellmStaticModels
  }
  dependsOn: [
    liteLlmOpenAiRoleAssignment
  ]
}

// Private DNS zone for the LiteLLM custom domain. ACA binds <liteLlmDomain>
// to its ingress for TLS termination but does NOT publish DNS for it. Without
// this zone, Foundry agent workloads get NXDOMAIN when resolving
// <liteLlmDomain> through Azure DNS (168.63.129.16).
//
// The zone covers the full FQDN with an A record at the apex (`@`) pointing
// to the ACA managed environment's Private Endpoint IP — the env has
// publicNetworkAccess: Disabled, so the public staticIp is blackholed and
// VNet workloads must reach the env via the PE NIC. The ACA frontend then
// routes by SNI to the LiteLLM container app's custom-domain binding.
module liteLlmDomainPrivateDnsZone 'br/public:avm/res/network/private-dns-zone:0.8.1' = if (phase2) {
  name: 'litellm-domain-private-dns-${resourceToken}'
  params: {
    tags: tags
    name: liteLlmDomain
    location: 'global'
    virtualNetworkLinks: [
      {
        virtualNetworkResourceId: vnet.outputs.VIRTUAL_NETWORK_RESOURCE_ID
        registrationEnabled: false
      }
    ]
    a: [
      {
        name: '@'
        ttl: 300
        aRecords: [
          {
            ipv4Address: liteLlm.outputs.containerAppsEnvironmentPrivateIp
          }
        ]
      }
    ]
  }
}

// Foundry ModelGateway connections target the LiteLLM custom domain directly.
// The Foundry account trusts its self-signed root through Key Vault.
module liteLlmConnectionDynamic '../modules/ai/connection-modelgateway-dynamic.bicep' = if (phase2) {
  name: 'lite-llm-connection-dynamic-${resourceToken}'
  params: {
    aiFoundryName: foundry!.outputs.FOUNDRY_NAME
    connectionName: 'model-gateway-litellm-${resourceToken}'
    apiKey: liteLlmMasterKey
    isSharedToAll: true
    gatewayName: 'litellm'
    targetUrl: 'https://${liteLlmDomain}'
  }
  dependsOn: [
    liteLlm
    liteLlmDomainPrivateDnsZone
    foundryKeyVaultSecretsUser
  ]
}

module liteLlmConnectionStatic '../modules/ai/connection-modelgateway-static.bicep' = if (phase2) {
  name: 'lite-llm-connection-static-${resourceToken}'
  params: {
    aiFoundryName: foundry!.outputs.FOUNDRY_NAME
    connectionName: 'model-gateway-litellm-${resourceToken}-static'
    apiKey: liteLlmMasterKey
    isSharedToAll: true
    gatewayName: 'litellm'
    targetUrl: 'https://${liteLlmDomain}'
    staticModels: litellmStaticModels
  }
  dependsOn: [
    liteLlm
    liteLlmDomainPrivateDnsZone
    foundryKeyVaultSecretsUser
  ]
}

module publicIpAddress 'br/public:avm/res/network/public-ip-address:0.12.0' = {
  params: {
    tags: tags
    location: location
    // Required parameters
    name: 'app-gateway-${resourceToken}-public-ip'
    // Non-required parameters
    availabilityZones: []
  }
}

module acaAppGateway '../modules/appgtw/application-gateway.bicep' = {
  name: 'aca-app-gateway-deployment-${resourceToken}'
  params: {
    tags: union(tags, {
      CostControl: 'Ignore'
      'hidden-title': 'LiteLLM public gateway'
    })
    location: location
    name: 'app-gateway-${resourceToken}'
    // Use the default ACA hostname so Application Gateway validates the
    // Microsoft-trusted ingress certificate independently of Foundry's CA trust.
    applicationFqdn: liteLlm.outputs.liteLlmAcaFqdn
    applicationGatewaySubnetId: vnet.outputs.VIRTUAL_NETWORK_SUBNETS.appGwSubnet.resourceId
    acaName: 'aca${resourceToken}'
    publicIpResourceId: publicIpAddress.outputs.resourceId
  }
}

module dashboard '../modules/dashboard/dashboard.bicep' = {
  name: 'dashboard-deployment-${resourceToken}'
  params: {
    location: location
    dashboardDisplayName: 'APIM Token Usage Dashboard for ${resourceToken}'
    applicationInsightsId: logAnalytics.outputs.APPLICATION_INSIGHTS_RESOURCE_ID
    applicationInsightsName: logAnalytics.outputs.APPLICATION_INSIGHTS_NAME
    logAnalyticsWorkspaceId: logAnalytics.outputs.LOG_ANALYTICS_WORKSPACE_RESOURCE_ID
  }
}

module models_policy '../modules/policy/models-policy.bicep' = {
  scope: subscription()
  name: 'policy-definition-deployment-${resourceToken}'
}

module models_policy_assignment '../modules/policy/models-policy-assignment.bicep' = {
  name: 'policy-assignment-deployment-${resourceToken}'
  params: {
    cognitiveServicesPolicyDefinitionId: models_policy.outputs.cognitiveServicesPolicyDefinitionId
    allowedCognitiveServicesModels: []
  }
}

output FOUNDRY_PROJECTS_CONNECTION_STRINGS string[] = phase2
  ? [
      projects[0].outputs.FOUNDRY_PROJECT_CONNECTION_STRING
      projects[1].outputs.FOUNDRY_PROJECT_CONNECTION_STRING
    ]
  : []
output FOUNDRY_PROJECT_NAMES string[] = phase2
  ? [
      projects[0].outputs.FOUNDRY_PROJECT_NAME
      projects[1].outputs.FOUNDRY_PROJECT_NAME
    ]
  : []
output CONFIG_VALIDATION_RESULT bool = valid_config
output CERT_CONFIG_VALIDATION_RESULT bool = valid_cert_config

output LITELLM_SWAGGER_URL string = 'http://${publicIpAddress.outputs.ipAddress}'
output LITELLM_UI_URL string = 'http://${publicIpAddress.outputs.ipAddress}/ui/login/'
output LITELLM_DOMAIN string = liteLlmDomain
output LITELLM_FOUNDRY_TARGET_URL string = phase2 ? 'https://${liteLlmDomain}' : ''
output LITELLM_INTERNAL_FQDN string = liteLlm.outputs.liteLlmAcaFqdn
output LITELLM_KEY string = liteLlmMasterKey
output PHASE string = phase2
  ? 'phase-2 (custom domain bound and Foundry private CA trust configured)'
  : 'phase-1 (LiteLLM bootstrap only — configure DNS, set LITELLM_DOMAIN, and rerun azd provision)'
