@subscriptionId={{$dotenv subscriptionId}}
@rg={{$dotenv rg}}
@foundryName={{$dotenv foundryName}}
@projectName={{$dotenv projectName}}
@vnetName={{$dotenv vnetName}}
@subnetName={{$dotenv subnetName}}
@subnetId={{$dotenv subnetId}}
@baseUrl=https://management.azure.com/subscriptions/{{subscriptionId}}/resourceGroups/{{rg}}/providers/Microsoft.CognitiveServices/accounts/

#<access token - use: az account get-access-token --resource=https://management.azure.com/ --query accessToken -o tsv>
@token={{$dotenv token}}

### create for hub
PUT {{baseUrl}}/{{foundryName}}/capabilityHosts/{{foundryName}}@aml_aiagentservice?api-version=2025-06-01
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties": {
    "capabilityHostKind": "Agents",
    "customerSubnet": "{{subnetId}}"
  }
}

### Get Hub Capability Hosts
GET {{baseUrl}}/{{foundryName}}/capabilityHosts/?api-version=2025-06-01
Authorization: Bearer {{token}}
Content-Type: application/json

### Delete Hub Capability Host
DELETE {{baseUrl}}/{{foundryName}}/capabilityHosts/{{foundryName}}@aml_aiagentservice?api-version=2025-06-01
Authorization: Bearer {{token}}

### Create Project Capability Host
PUT {{baseUrl}}/{{foundryName}}/projects/{{projectName}}/capabilityHosts/projcaphost?api-version=2025-04-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "properties": {
    "description": "This is a test capability host for project",
    "capabilityHostKind": "Agents",
    "vectorStoreConnections": [
      "project-search-vsovqlu7h7d7c"
    ],
    "storageConnections": [
      "projstoragevsovqlu7h7d7c"
    ],
    "threadStorageConnections": [
      "project-cosmosdb-vsovqlu7h7d7c"
    ],
  }
}

### Get Project Capability Host
GET {{baseUrl}}/{{foundryName}}/projects/{{projectName}}/capabilityHosts?api-version=2025-04-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

### DELETE Project Capability Host
DELETE {{baseUrl}}/{{foundryName}}/projects/{{projectName}}/capabilityHosts/projcaphost?api-version=2025-04-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

### Get Project Connections
GET {{baseUrl}}/{{foundryName}}/projects/{{projectName}}/connections?api-version=2025-04-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

### Patch connection
PATCH {{baseUrl}}/{{foundryName}}/projects/{{projectName}}/connections/emissionscopilotcogdev2bntpnqkfowt4?api-version=2025-04-01-preview
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "properties": {
    "authType": "AAD",
    // Only include the properties you want to update
    "target": "https://2nkn24g7-8081.use2.devtunnels.ms/",
  }
}

### chat completion
POST  https://2nkn24g7-8081.use2.devtunnels.ms/openai/deployments/gtp-35-turbo/chat/completions?api-version=2024-02-15-preview
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "messages": [
    { "role": "system", "content": "You are an AI assistant that helps people." },
    { "role": "user", "content": "Hello, how can I use Azure OpenAI?" }
  ],
  "max_tokens": 256,
  "temperature": 0.7,
  "top_p": 1
}

