param location string
param name string

@allowed([
  'Public'
  'Private'
])
param deploymentMode string

param subnetResourceId string = ''

@secure()
param adminPassword string

param technitiumImage string
param resourceToken string
param tags object = {}

var isPublic = deploymentMode == 'Public'
var storageAccountName = 'dns${resourceToken}'
var fileShareName = 'technitium'
var publicDnsLabel = 'technitium-${resourceToken}'

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {
  name: storageAccountName
  location: location
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
  properties: {
    allowBlobPublicAccess: false
    allowSharedKeyAccess: true
    minimumTlsVersion: 'TLS1_2'
  }
  tags: union(tags, { SecurityControl: 'ignore' })
}

resource fileService 'Microsoft.Storage/storageAccounts/fileServices@2023-05-01' = {
  parent: storageAccount
  name: 'default'
}

resource fileShare 'Microsoft.Storage/storageAccounts/fileServices/shares@2023-05-01' = {
  parent: fileService
  name: fileShareName
  properties: {
    enabledProtocols: 'SMB'
    shareQuota: 5
  }
}

resource containerGroup 'Microsoft.ContainerInstance/containerGroups@2023-05-01' = {
  name: name
  location: location
  properties: {
    containers: [
      {
        name: 'technitium'
        properties: {
          image: technitiumImage
          environmentVariables: [
            {
              name: 'DNS_SERVER_DOMAIN'
              value: 'dns.${resourceToken}.internal'
            }
            {
              name: 'DNS_SERVER_ADMIN_PASSWORD'
              secureValue: adminPassword
            }
            {
              name: 'DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS'
              value: 'true'
            }
            {
              name: 'DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT'
              value: 'true'
            }
            {
              name: 'DNS_SERVER_WEB_SERVICE_HTTP_TO_TLS_REDIRECT'
              value: 'true'
            }
            {
              name: 'DNS_SERVER_RECURSION'
              value: isPublic ? 'Deny' : 'AllowOnlyForPrivateNetworks'
            }
            {
              name: 'DNS_SERVER_FORWARDERS'
              value: '168.63.129.16'
            }
            {
              name: 'DNS_SERVER_FORWARDER_PROTOCOL'
              value: 'Udp'
            }
            {
              name: 'DNS_SERVER_ENABLE_BLOCKING'
              value: 'false'
            }
            {
              name: 'DNS_SERVER_LOG_FOLDER_PATH'
              value: '/etc/dns/logs'
            }
          ]
          ports: [
            {
              port: 53
              protocol: 'UDP'
            }
            {
              port: 53443
              protocol: 'TCP'
            }
          ]
          resources: {
            requests: {
              cpu: 1
              memoryInGB: 2
            }
          }
          volumeMounts: [
            {
              name: 'config'
              mountPath: '/etc/dns'
              readOnly: false
            }
          ]
        }
      }
    ]
    ipAddress: {
      type: deploymentMode
      dnsNameLabel: isPublic ? publicDnsLabel : null
      autoGeneratedDomainNameLabelScope: isPublic ? 'TenantReuse' : null
      ports: [
        {
          port: 53
          protocol: 'UDP'
        }
        {
          port: 53443
          protocol: 'TCP'
        }
      ]
    }
    osType: 'Linux'
    restartPolicy: 'Always'
    subnetIds: isPublic
      ? null
      : [
          {
            id: subnetResourceId
          }
        ]
    volumes: [
      {
        name: 'config'
        azureFile: {
          shareName: fileShare.name
          storageAccountName: storageAccount.name
          storageAccountKey: storageAccount.listKeys().keys[0].value
          readOnly: false
        }
      }
    ]
  }
  tags: tags
}

var dnsServerIp = containerGroup.properties.ipAddress.ip
var dnsServerFqdn = isPublic ? containerGroup.properties.ipAddress.fqdn : ''
var dnsApiHost = isPublic ? dnsServerFqdn : dnsServerIp

output CONTAINER_GROUP_NAME string = containerGroup.name
output DNS_SERVER_IP string = dnsServerIp
output DNS_SERVER_FQDN string = dnsServerFqdn
output DNS_API_URL string = 'https://${dnsApiHost}:53443'
