"""Configuration loader for ai-gateway-quota live integration tests.

Reads, in priority order:
  1. tests/.env (preferred for local test runs)
  2. options-infra/ai-gateway-quota/.env (generated by deployment hooks)
  3. process environment

Required to run tests: APIM_GATEWAY_URL and TENANT_ID. For token acquisition,
either provide TEST_ACCESS_TOKEN, provide CLIENT_ID + CLIENT_SECRET (or Azure
SDK-style AZURE_CLIENT_ID + AZURE_CLIENT_SECRET), or sign in with `az login` for
DefaultAzureCredential fallback.
"""

from __future__ import annotations

import os
from pathlib import Path

from dotenv import load_dotenv

_TESTS_DIR = Path(__file__).resolve().parent.parent
_OPTION_DIR = _TESTS_DIR.parent

# Prefer tests/.env over the deployment-level .env; do not let the parent file
# overwrite explicit test-specific settings.
load_dotenv(_OPTION_DIR / '.env', override=False)
load_dotenv(_TESTS_DIR / '.env', override=True)


def _optional(name: str, default: str = '') -> str:
    return os.environ.get(name, default).strip() or default


def _first(*names: str, default: str = '') -> str:
    for name in names:
        value = _optional(name)
        if value:
            return value
    return default


GATEWAY_URL: str = _optional('APIM_GATEWAY_URL').rstrip('/')
TENANT_ID: str = _optional('TENANT_ID')
CLIENT_ID: str = _first('CLIENT_ID', 'AZURE_CLIENT_ID')
CLIENT_SECRET: str = _first('CLIENT_SECRET', 'AZURE_CLIENT_SECRET')

# Optional — only needed if the deployed gateway requires APIM subscription keys.
APIM_SUBSCRIPTION_KEY: str = _first('APIM_SUBSCRIPTION_KEY', 'APIM_API_KEY')

# Optional — APIM SKU the gateway is deployed on. Used to skip tests that
# require features only available on higher tiers (e.g. the OpenAI v1 API
# surface needs 100+ API operations, which only StandardV2 and Premium
# support). Leave empty to attempt every test regardless of tier.
APIM_SKU: str = _optional('APIM_SKU')

# Optional explicit bearer token. When set, the suite skips Azure credentials.
TEST_ACCESS_TOKEN: str = _optional('TEST_ACCESS_TOKEN')

# This repo's passthrough API path carries the Azure OpenAI `/openai` segment.
API_URL: str = f'{GATEWAY_URL}/inference/openai' if GATEWAY_URL else ''

# Static deployment discovery operations are attached at `/inference` and
# `/azure/openai`, not under the passthrough `/inference/openai` catch-all.
DISCOVERY_API_URL: str = f'{GATEWAY_URL}/inference' if GATEWAY_URL else ''
AZURE_OPENAI_API_URL: str = f'{GATEWAY_URL}/azure/openai' if GATEWAY_URL else ''
CONFIG_JSON_URL: str = f'{GATEWAY_URL}/ai-gateway/config.json' if GATEWAY_URL else ''
CONFIG_UPDATE_URL: str = f'{GATEWAY_URL}/ai-gateway/config/update' if GATEWAY_URL else ''

# Azure OpenAI / cognitive-services audience for token acquisition.
AUDIENCE: str = _optional('AUDIENCE', 'https://cognitiveservices.azure.com')

# API version used for chat-completion and audio routes.
API_VERSION: str = _optional('API_VERSION', '2025-03-01-preview')

# Defaults match ai-gateway-quota/main.bicepparam self-contained deployment.
DEFAULT_MODEL: str = _optional('TEST_MODEL', 'gpt-4.1-mini')
FAILOVER_MODEL: str = _optional('TEST_FAILOVER_MODEL', DEFAULT_MODEL)
DEFAULT_CONTRACT_NAME: str = _optional('TEST_CONTRACT', 'Team Alpha')


def validate_required_config() -> None:
    missing = [name for name, value in {'APIM_GATEWAY_URL': GATEWAY_URL, 'TENANT_ID': TENANT_ID}.items() if not value]
    if CLIENT_ID and not CLIENT_SECRET:
        missing.append('CLIENT_SECRET')
    if CLIENT_SECRET and not CLIENT_ID:
        missing.append('CLIENT_ID')
    if missing:
        raise RuntimeError(
            'Required test configuration is missing: '
            + ', '.join(sorted(set(missing)))
            + '. Set values in tests/.env, the deployment .env, or the process environment.'
        )
