output "apim_gateway_url" {
  value = azurerm_api_management.apim.gateway_url
}

output "inference_api_url" {
  value = "${azurerm_api_management.apim.gateway_url}/openai"
}

output "config_viewer_url" {
  value = "${azurerm_api_management.apim.gateway_url}/gateway/config"
}

output "apim_name" {
  value = azurerm_api_management.apim.name
}

output "apim_principal_id" {
  value = azurerm_api_management.apim.identity[0].principal_id
}

output "resource_group_name" {
  value = azurerm_resource_group.rg.name
}

output "pool_names" {
  value = concat(module.advanced_backends.ptu_pool_names, module.advanced_backends.payg_pool_names)
}

output "has_ptu_deployments" {
  value = module.advanced_backends.has_ptu_deployments
}

output "contract_map_json" {
  value     = local.contract_map_json
  sensitive = false
}

# Generate .env file for the test notebook — infra config only (safe to overwrite)
resource "local_file" "env_file" {
  filename = "${path.module}/../.env"
  content  = join("\n", concat(
    [
      "# Generated by Terraform — re-run 'terraform apply' to refresh",
      "",
      "APIM_GATEWAY_URL=${azurerm_api_management.apim.gateway_url}",
      "APIM_API_URL=${azurerm_api_management.apim.gateway_url}/openai",
      "TENANT_ID=${var.tenant_id}",
      "",
    ],
    flatten([
      for c in var.access_contracts : [
        "TEAM_${upper(replace(c.name, " ", "_"))}_APP_ID=${length(c.identities) > 0 ? c.identities[0].value : ""}",
      ]
    ]),
    [""]
  ))
}

# Generate .env.secrets template — only if it doesn't already exist
resource "local_file" "env_secrets_template" {
  filename = "${path.module}/../.env.secrets"
  content  = join("\n", concat(
    [
      "# Team secrets — fill in manually, this file is not overwritten by Terraform",
      "",
    ],
    flatten([
      for c in var.access_contracts : [
        "TEAM_${upper(replace(c.name, " ", "_"))}_SECRET=",
      ]
    ]),
    [""]
  ))

  lifecycle {
    ignore_changes = [content]
  }
}
